#
class ssh::params {

  $allow_groups              = ''
  $allow_tcp_forwarding      = 'no'
  $allow_users               = ''
  $ciphers                   = 'aes128-ctr,aes192-ctr,aes256-ctr'
  $client_alive_count_max    = '0'
  $client_alive_interval     = '300'
  $deny_groups               = ''
  $deny_users                = ''
  $hostbased_authentication  = 'no'
  $ignore_rhosts             = 'yes'
  $listen_address            = '0.0.0.0'
  $log_level                 = 'VERBOSE'
  $macs                      = 'hmac-sha1'
  $max_auth_tries            = '4'
  $package_ensure            = 'present'
  $package_name              = 'openssh-server'
  $permit_empty_passwords    = 'no'
  $permit_root_login         = 'no'
  $permit_user_environment   = 'no'
  $port                      = '22'
  $protocol                  = '2'
  $rhosts_rsa_authentication = 'no'
  $service_enable            = true
  $service_ensure            = 'running'
  $ssh_banner                = '/etc/motd'
  $sshd_config_template      = 'ssh/sshd_config.erb'
  $x11_forwarding            = 'no'
}
